Start loading command groups from mycmd-lib
This is in progress:
- does not yet disocver the commands
- `mycmd:command_group.load_command_group` now returns an error if it
has been loaded for a different path

Fixes a bug with how I was handling checking nullglob.

Re-ordered the tests in my `mycmd-lib-test`.

Disabled the logging command group tests for now.

diff --git a/mycmd/mycmd-lib b/mycmd/mycmd-lib
--- a/mycmd/mycmd-lib
+++ b/mycmd/mycmd-lib
@@ -36,10 +36,38 @@ if [[ ! -v _MYCMD_LOADING_LIB ]]; then
 fi
 
 # Once the Loading Base library is loaded, we can use its functionality to load everything else
+# TODO: Minimize this list to only those that are directly called from mycmd-lib
 mycmd.load_mycmd_lib_support_lib "output"
 mycmd.load_mycmd_lib_support_lib "environment"
 mycmd.load_mycmd_lib_support_lib "event-lifecycle"
 mycmd.load_mycmd_lib_support_lib "platform-support"
+mycmd.load_mycmd_lib_support_lib "pathname"
+mycmd.load_mycmd_lib_support_lib "command"
+mycmd.load_mycmd_lib_support_lib "command-group"
+
+# ------------------------------------------------------------------------------
+# Configuring the MyCmd top-level command group
+function mycmd:discover_command_groups_and_commands_callback() {
+    local -r full_path="${1}"
+    local -r fully_qualifed_name="${2}"
+    local -n _dirs_ref="${3}"
+    local -n _files_ref="${4}"
+
+    if mycmd:command_group.directory_contains_command_group "${full_path}"; then
+        if ! mycmd:command_group.load_command_group "${full_path}"; then
+            mycmd.error "Error loading command group '${fully_qualifed_name}' from '${full_path}'."
+            return 1
+        fi
+    fi
+
+    # TODO: Load potential commands in the directory
+}
+
+function mycmd:discover_command_groups_and_commands() {
+    mycmd:pathname.walk_path "mycmd" mycmd:discover_command_groups_and_commands_callback
+}
+
+mycmd:discover_command_groups_and_commands
 
 # ------------------------------------------------------------------------------
 # Finalization and Clean Up
