Support system and user directories
This is the start of support of having both system and user MyCmd
directories. One step closer to making this easier for others to install
and consume.

diff --git a/bin/mycmd b/bin/mycmd
--- a/bin/mycmd
+++ b/bin/mycmd
@@ -25,23 +25,52 @@ set -o nounset -o errexit -o errtrace -o pipefail
 readonly _MYCMD_SELF_FILE="${BASH_SOURCE[0]}"
 
 # ------------------------------------------------------------------------------
-# Set MYCMD_BASE_DIR
+# Set MYCMD_SYSTEM_BASE_DIR and MYCMD_USER_BASE_DIR
 #
-#   Defaults to ~/mycmd; have MYCMD_BASE_DIR set before launching to override
-#   this.
-if [[ -z "${MYCMD_BASE_DIR-}" || ! -d "${MYCMD_BASE_DIR}" ]]; then
-    readonly MYCMD_BASE_DIR="${HOME}/mycmd"
+#   MYCMD_SYSTEM_BASE_DIR defaults to the mycmd directory that is parallel to
+#   the bin directory that this mycmd script is in; have MYCMD_SYSTEM_BASE_DIR
+#   set before launching to override this, however this directory must include
+#   the mycmd-lib file that is included in the MyCmd distribution.
+if [[ -z "${MYCMD_SYSTEM_BASE_DIR-}" || ! -d "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
+	_MYCMD_BIN_DIR=$(cd "$(dirname "${_MYCMD_SELF_FILE}")" &>/dev/null && pwd -P)
+	readonly _MYCMD_BIN_DIR
 
-    if [[ ! -d "${MYCMD_BASE_DIR}" ]]; then
-        echo >&2 "Default MyCmd base directory '$HOME/mycmd' not found."
-        exit 1
-    fi
-
-    export MYCMD_BASE_DIR
+    MYCMD_SYSTEM_BASE_DIR=$(cd "${_MYCMD_BIN_DIR}/../mycmd" &> /dev/null && pwd -P)
+    readonly MYCMD_SYSTEM_BASE_DIR
+    export MYCMD_SYSTEM_BASE_DIR
 fi
 
-# shellcheck source=../shell/mycmd-lib
-source "${MYCMD_BASE_DIR}/mycmd-lib"
+#   MYCMD_USER_BASE_DIR defaults to ~/mycmd; have MYCMD_USER_BASE_DIR set before
+#   launching to override this.
+#
+#   The directory specified in MYCMD_USER_BASE_DIR is not required to currently
+#   exist, to allow the user to run MyCmd without first having locally defined
+#   command groups and commands.
+if [[ -z "${MYCMD_USER_BASE_DIR-}" ]]; then
+    MYCMD_USER_BASE_DIR="${HOME}/mycmd"
+fi
+
+if [[ -d "${MYCMD_USER_BASE_DIR}" ]]; then
+    readonly MYCMD_USER_BASE_DIR
+    export MYCMD_USER_BASE_DIR
+else
+    unset MYCMD_USER_BASE_DIR
+fi
+
+# ------------------------------------------------------------------------------
+# Validate MYCMD_SYSTEM_BASE_DIR setting and source MyCmd Base Library
+if [[ ! -d "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
+    echo >&2 "MYCMD_SYSTEM_BASE_DIR setting of ${MYCMD_SYSTEM_BASE_DIR} invalid, as directory does not exist."
+    exit 1
+fi
+
+if [[ ! -e "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
+    echo >&2 "MYCMD_SYSTEM_BASE_DIR setting of ${MYCMD_SYSTEM_BASE_DIR} invalid, as required file mycmd-lib is missing."
+    exit 1
+fi
+
+# shellcheck source=../mycmd/mycmd-lib
+source "${MYCMD_SYSTEM_BASE_DIR}/mycmd-lib"
 
 # ------------------------------------------------------------------------------
 # Common Command and Group Parsing Support
@@ -53,10 +82,11 @@ function display_command_or_group_parts() {
     local -r command_or_group_path="${1}"
     local -r output_prefix="${2}"
 
-    if [[ "${command_or_group_path}" = "${MYCMD_BASE_DIR}" ]]; then
+    if [[ "${command_or_group_path}" = "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
         mycmd.output "${MYCMD_DESC}"
     fi
 
+    mycmd.trace "Calling with '${command_or_group_path}'."
     local -r relative_path="$(mycmd.path_relative_to_mycmd_base "${command_or_group_path}")"
 
     local parts
@@ -107,6 +137,7 @@ function command_or_group_version_from_comment() {
 # Command Handling Support
 function command_short_help() {
     local -r command_path="${1}"
+
     local short_help
     short_help="$(command_or_group_short_help_from_comment "${command_path}")"
     readonly short_help
@@ -134,15 +165,28 @@ function command_version() {
 function command_group_library_file_path() {
     local -r command_group_path="${1}"
     local -r command_group_name="$(basename "${command_group_path}")"
-    echo "${command_group_path}/${command_group_name}-lib"
+
+    local library_file="${command_group_path}/${command_group_name}-lib"
+    if [[ ! "${command_group_path}" = /* ]]; then
+        if ! library_file=$(_get_first_matching_relative_path_in_system_or_user_dir "${library_file}"); then
+            mycmd.log "Error getting library file for command group ${command_group_path}"
+            return 1
+        fi
+    fi
+    readonly library_file
+
+    echo "${library_file}"
 }
 
 mycmd.init_bin realpath
-function path_relative_to_command_group() {
-    local -r command_group_path="${1}"
-	local -r full_path="${2}"
-	local -r relative_path="$("${MYCMD_BIN[realpath]}" --relative-to="${command_group_path}" "${full_path}")"
-	echo "${relative_path}"
+function canonicalize_path() {
+    local -r path_to_resolve="${1}"
+
+    if [[ -v missing_ok ]]; then
+        "${MYCMD_BIN[realpath]}" --canonicalize-missing --quiet --logical "${path_to_resolve}"
+    else
+        "${MYCMD_BIN[realpath]}" --canonicalize-existing --quiet --logical "${path_to_resolve}"
+    fi
 }
 
 # Some commands are only used when called from other scripts and thus shouldn't be
@@ -155,7 +199,8 @@ function should_hide_command() {
 
 function command_group_short_help() {
     local -r command_group_path="${1}"
-    local -r group_library_file="$(command_group_library_file_path ${command_group_path})"
+    local -r group_library_file="$(command_group_library_file_path "${command_group_path}")"
+
     local short_help
     short_help="$(command_or_group_short_help_from_comment "${group_library_file}")"
     readonly short_help
@@ -163,17 +208,26 @@ function command_group_short_help() {
     if [[ -n "${short_help-}" ]]; then
         echo "${short_help}"
     else
-        display_command_or_group_parts "${command_group_path}" "${GROUP_DESC}"
+        display_command_or_group_parts "${group_library_file}" "${GROUP_DESC}"
     fi
 }
 
 mycmd.init_bin find
+function _find_command_group_children_in_system_or_user_directories() {
+    local -r command_group_relative_path="${1}"
+    local -a paths_to_search
+
+    readarray -t paths_to_search < <(_get_matching_relative_paths_in_system_or_user_dir "${command_group_relative_path}")
+
+    "${MYCMD_BIN[find]}" -L "${paths_to_search[@]}" -type f -executable -print0
+}
+
 function find_command_group_children() {
-    local -r command_group_path="${1}"
+    local -r command_group_relative_path="${1}"
     local -n direct_child_groups_ref="${2}"
     local -n direct_child_commands_ref="${3}"
 
-    mycmd.trace "Finding children for '${command_group_path}'."
+    mycmd.trace "Finding children for '${command_group_relative_path}'."
 
     local potential_descendant_command
     local relative_path
@@ -184,7 +238,7 @@ function find_command_group_children() {
         mycmd.trace "Examining '${potential_descendant_command}'."
 
         if ! should_hide_command "${potential_descendant_command}"; then
-            relative_path="$(path_relative_to_command_group "${command_group_path}" "${potential_descendant_command}")"
+            relative_path="$(mycmd.path_relative_to_mycmd_base_with_command_group "${potential_descendant_command}" "${command_group_relative_path}")"
             command_name=$(basename "${relative_path}")
 
             mycmd.trace "Examining '${relative_path}' with command name '${command_name}'."
@@ -197,11 +251,11 @@ function find_command_group_children() {
                 subgroup="${relative_path%%/*}"
 
                 if [[ ! -v direct_child_groups_ref["${subgroup}"] ]]; then
-                    direct_child_groups_ref["${subgroup}"]="$(command_group_short_help "${command_group_path}/${subgroup}")"
+                    direct_child_groups_ref["${subgroup}"]="$(command_group_short_help "${command_group_relative_path}/${subgroup}")"
                 fi
             fi
         fi
-    done < <( "${MYCMD_BIN[find]}" -L "${command_group_path}" -type f -executable -print0)
+    done < <(_find_command_group_children_in_system_or_user_directories "${command_group_relative_path}")
 
     mycmd.trace "Found the following commands: '${!direct_child_commands_ref[*]}'"
     mycmd.trace "Found the following immediate subgroups: '${!direct_child_groups_ref[*]}'"
@@ -278,7 +332,14 @@ function summarize_command_group_children() {
     local output_line
     local key
 
-    find_command_group_children "${command_group_path}" direct_child_groups direct_child_commands
+    local command_group_relative_path
+    if ! command_group_relative_path="$(mycmd.path_relative_to_mycmd_base "${command_group_path}")"; then
+        mycmd.log "Error getting relative path."
+        return 1
+    fi
+    readonly command_group_relative_path
+
+    find_command_group_children "${command_group_relative_path}" direct_child_groups direct_child_commands
 
     print_section direct_child_groups \
         "The following command groups are defined:" \
@@ -293,7 +354,7 @@ function summarize_command_group_children() {
 
 function command_group_help() {
     local -r command_group_path="${1}"
-    local -r group_library_file="$(command_group_library_file_path ${command_group_path})"
+    local -r group_library_file="$(command_group_library_file_path "${command_group_path}")"
 
     display_command_or_group_parts "${command_group_path}" "${GROUP_DESC}"
     command_or_group_help_from_comment "${group_library_file}"
@@ -302,7 +363,7 @@ function command_group_help() {
 
 function command_group_version() {
     local -r command_group_path="${1}"
-    local -r group_library_file="$(command_group_library_file_path ${command_group_path})"
+    local -r group_library_file="$(command_group_library_file_path "${command_group_path}")"
 
     command_or_group_version_from_comment "${group_library_file}"
 }
@@ -318,12 +379,19 @@ function mycmd_usage() {
     mycmd.output "\n  See the help for the individual command groups for further details."
     mycmd.output "\n${mycmd_name} <command_group>... <command> [-h | --help] [-v | --version] [arguments]"
     mycmd.output "\n  See the help for the individual sub commands for further details."
+    mycmd.output "\nThe following environment variables are recognized, if set:\n"
+    mycmd.output "MYCMD_SYSTEM_BASE_DIR    - the base directory for system defined MyCmd Command Groups."
+    mycmd.output "MYCMD_USER_BASE_DIR      - the base directory for user defined MyCmd Command Groups. Defaults to $HOME/mycmd if not set, if the directory exists."
+    mycmd.output "MYCMD_SHELL_TRACE        - enables Bash's xtrace (set -x) for the executing command."
+    mycmd.output "MYCMD_SHELL_VERBOSE      - enables Bash's verbose mode (set -v) for the executing command."
+    mycmd.output "MYCMD_DEBUG              - enables output of debug logging in the executing command."
+    mycmd.output "MYCMD_TRACE              - enables output of trace logging in the executing command."
 }
 
 function mycmd_help() {
     command_or_group_help_from_comment "${_MYCMD_SELF_FILE}"
     mycmd_usage
-    summarize_command_group_children "${MYCMD_BASE_DIR}"
+    summarize_command_group_children "${MYCMD_SYSTEM_BASE_DIR}"
 }
 
 function mycmd_version() {
@@ -366,8 +434,8 @@ function output_zsh_completion_for_command_group() {
 function output_zsh_completion() {
     local -r full_path="${1}"
 
-    if [[ "${full_path}" = "${MYCMD_BASE_DIR}" ]]; then
-        output_zsh_completion_for_command_group "${MYCMD_BASE_DIR}"
+    if [[ "${full_path}" = "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
+        output_zsh_completion_for_command_group "${MYCMD_SYSTEM_BASE_DIR}"
     elif [[ -d "${full_path}" ]]; then
         output_zsh_completion_for_command_group "${full_path}"
     else
@@ -387,7 +455,7 @@ function help() {
     if [[ "${found_non_flags}" = "true" ]]; then
         mycmd.trace "Skipping printing help because an invalid command was found."
         return 0
-    elif [[ "${full_path}" = "${MYCMD_BASE_DIR}" ]]; then
+    elif [[ "${full_path}" = "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
         mycmd_help
     elif [[ -d "${full_path}" ]]; then
         command_group_help "${full_path}"
@@ -405,7 +473,7 @@ function version() {
     if [[ "${found_non_flags}" = "true" ]]; then
         mycmd.trace "Skipping printing version because an invalid command was found."
         return 0
-    elif [[ "${full_path}" = "${MYCMD_BASE_DIR}" ]]; then
+    elif [[ "${full_path}" = "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
         mycmd_version
     elif [[ -d "${full_path}" ]]; then
         command_group_version "${full_path}"
@@ -416,27 +484,70 @@ function version() {
     exit 0
 }
 
+function _get_matching_relative_paths_in_system_or_user_dir() {
+    local -r relative_path="${1}"
+    local -r first_only="${2-:false}"
+
+    local system_relative_path
+    if ! system_relative_path="$(missing_ok=1 canonicalize_path "${MYCMD_SYSTEM_BASE_DIR}/${relative_path}")"; then
+        mycmd.log "Error resolving possible system path for relative path '${relative_path}'"
+        return 1
+    fi
+    readonly system_relative_path
+
+    mycmd.trace "Examining full system path of '${system_relative_path}'."
+
+    if [[ -e "${system_relative_path}" ]]; then
+        echo "${system_relative_path}"
+
+        if [[ "${first_only}" = "true" ]]; then
+            return 0
+        fi
+    fi
+
+    if [[ -v MYCMD_USER_BASE_DIR ]]; then
+        local user_relative_path
+        if ! user_relative_path="$(missing_ok=1 canonicalize_path "${MYCMD_USER_BASE_DIR}/${relative_path}")"; then
+            mycmd.log "Error resolving possible user path for relative path '${relative_path}'"
+            return 1
+        fi
+
+        mycmd.trace "Examining full user path of '${user_relative_path}'."
+
+        if [[ -e "${user_relative_path}" ]]; then
+            echo "${user_relative_path}"
+            return 0
+        fi
+    fi
+
+    return 1
+}
+
+function _get_first_matching_relative_path_in_system_or_user_dir() {
+    local -r relative_path="${1}"
+
+    _get_matching_relative_paths_in_system_or_user_dir "${relative_path}" "true" ; return $?
+}
+
 # ------------------------------------------------------------------------------
 # Main
 function main() {
-    local full_path="${MYCMD_BASE_DIR}"
+    local full_path="${MYCMD_SYSTEM_BASE_DIR}"
+    local relative_path
+    local possible_full_path
     local element
 
     while (($# > 0)); do
         element="${1}"
-        mycmd.trace "Examining path component '${element}' at full path '${full_path}/${element}'."
+        relative_path="${relative_path-}${relative_path:+/}${element}"
 
-        if [[ -d "${full_path}/${element}" ]]; then
-            full_path="${full_path}/${element}"
-            mycmd.trace "Found command group at full path '${full_path}'."
+        mycmd.trace "Examining path component '${element}'; with relative path of '${relative_path}'"
 
+        if possible_full_path="$(_get_first_matching_relative_path_in_system_or_user_dir "${relative_path}")"; then
+            full_path="${possible_full_path}"
             shift
-        elif [[ -f "${full_path}/${element}" ]]; then
-            full_path="${full_path}/${element}"
-            mycmd.trace "Found potential command at full path '${full_path}'."
 
-            shift
-            break
+            [[ -f "${full_path}" ]] && break
         else
             break
         fi
@@ -470,7 +581,7 @@ function main() {
         # group
         if (($# > 0)); then
             mycmd.err_exit 1 "MyCmd command '${1}' in ${full_path} does not exist."
-        elif [[ "${full_path}" = "${MYCMD_BASE_DIR}" ]]; then
+        elif [[ "${full_path}" = "${MYCMD_SYSTEM_BASE_DIR}" ]]; then
             mycmd_help
         else
             command_group_help "${full_path}"
diff --git a/mycmd/mycmd-lib b/mycmd/mycmd-lib
--- a/mycmd/mycmd-lib
+++ b/mycmd/mycmd-lib
@@ -93,15 +93,9 @@ function mycmd.err_exit() {
 }
 
 # ------------------------------------------------------------------------------
-# Set MYCMD_BASE_DIR
-#
-#   If not set, or set to a non-existent directory, fall back and set
-#   MYCMD_BASE_DIR to the directory this file is in.
-if [[ -z "${MYCMD_BASE_DIR-}" || ! -d "${MYCMD_BASE_DIR}" ]]; then
-	MYCMD_BASE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
-	readonly MYCMD_BASE_DIR
-
-	mycmd.trace "Setting MYCMD_BASE_DIR to: ${MYCMD_BASE_DIR}"
+# Validate system environment
+if [[ -z "${MYCMD_SYSTEM_BASE_DIR-}" ]]; then
+	mycmd.err_exit 1 "Required environment variable MYCMD_SYSTEM_BASE_DIR is not set."
 fi
 
 # -------------------------------------------------------------------------------
@@ -393,9 +387,28 @@ function mycmd.init_bin() {
 # ------------------------------------------------------------------------------
 # MyCmd Sourcing Support
 
+# mycmd._source_lib_by_path
+#   Source the library if it exists.
+function mycmd._source_lib_by_path_if_found() {
+	local -r library_full_path="${1}"; shift
+
+	if [[ -e "${library_full_path}" ]]; then
+		# shellcheck source=/dev/null
+		source "${library_full_path}" "$@"
+
+		# Run any remaining deferreds for the startup for the library
+		_mycmd.run_startup_deferreds "${library_full_path}"
+
+		return 0
+	else
+		return 1
+	fi
+}
+
 # mycmd.source_mycmd_lib
 #   Explicitly source a MyCmd library and its dependencies by providing the
-#   directory name of the MyCmd library relative to the MYCMD_BASE_DIR.
+#   directory name of the MyCmd library relative to either first
+#   MYCMD_SYSTEM_BASE_DIR or, secondly, MYCMD_USER_BASE_DIR.
 #
 #   For example, to source the library in ~/mycmd/requests/service1, call this
 #   like this:
@@ -411,21 +424,35 @@ function mycmd.source_mycmd_lib() {
 	IFS="/" read -a dir_parts <<<"${library_path}"
 	readonly dir_parts
 
-	# Start at the base directory
-	local lib_dir="${MYCMD_BASE_DIR}"
+	# Start at the system base directory
+	local lib_dir="${MYCMD_SYSTEM_BASE_DIR}"
+
+	# And the user base directory, if it exists
+	if [[ -n "${MYCMD_USER_BASE_DIR-}" ]]; then
+		local local_lib_dir="${MYCMD_USER_BASE_DIR}"
+	fi
+
 	local dir
 	for dir in "${dir_parts[@]}"; do
 		lib_dir="${lib_dir}/${dir}"
+		if [[ -v local_lib_dir ]]; then
+			local_lib_dir="${local_lib_dir}/${dir}"
+		fi
 
-		# Look for a script named <dirname>-lib in <dirname>
+		# Look for a command group library named <dirname>-lib in <dirname>
 		local lib_script="${lib_dir}/${dir}-lib"
 
-		if [[ -e "${lib_script}" ]]; then
-			# shellcheck source=/dev/null
-			source "${lib_script}" "$@"
-
-			# Run any remaining deferreds for the startup
-			_mycmd.run_startup_deferreds "${lib_script}"
+		# First check in MYCMD_SYSTEM_BASE_DIR
+		if mycmd._source_lib_by_path_if_found "${lib_script}" "${@}"; then
+			if [[ -v local_lib_dir ]]; then
+				# If found, source the local overrides file from MYCMD_USER_BASE_DIR, if it exists
+				local local_lib_override="${local_lib_dir}/${dir}-local-lib"
+				mycmd._source_lib_by_path_if_found "${local_lib_override}" "${@}" || true
+			fi
+		elif [[ -v local_lib_dir ]]; then
+			# Otherwise, check in MYCMD_USER_BASE_DIR
+			local local_lib_script="${local_lib_dir}/${dir}-lib"
+			mycmd._source_lib_by_path_if_found "${local_lib_script}" "${@}" || true
 		fi
 	done
 }
@@ -436,50 +463,103 @@ function _mycmd.running_cmd_name() {
 	basename "${running_cmd}"
 }
 
-function _mycmd.running_cmd_relative_path() {
-	local -r running_cmd_dir="$(dirname "${BASH_SOURCE[-1]}")"
-	mycmd.path_relative_to_mycmd_base "${running_cmd_dir}"
+# mycmd._path_relative_to_directory
+#   Given an absolute path to a command or command group, output the relative path to
+#   the base directory specified.
+#
+#   Returns 1 if the specified path is not a descendant of the base directory.
+mycmd.defer_at_startup mycmd.init_bin realpath
+function mycmd._path_relative_to_directory() {
+	local -r full_path="${1}"
+	local -r base_path="${2}"
+
+	local -r relative_path="$("${MYCMD_BIN[realpath]}" --relative-to="${base_path}" "${full_path}")"
+
+	# If the relative path starts with .., it is not a descendant
+	if [[ "${relative_path}" = ..* ]]; then
+		return 1
+	else
+		echo "${relative_path}"
+		return 0
+	fi
 }
 
+# mycmd.path_relative_to_mycmd_base
+#   Given an absolute path to a command or command group, return the relative path
+#   in comparison to either MYCMD_SYSTEM_BASE_DIR or MYCMD_USER_BASE_DIR.
 mycmd.defer_at_startup mycmd.init_bin realpath
-function mycmd.path_relative_to_mycmd_base() {
+function mycmd.path_relative_to_mycmd_base_with_command_group() {
+	# We assume that full_path is going to be a canonicalized absolute path
 	local -r full_path="${1}"
-	local -r relative_path="$("${MYCMD_BIN[realpath]}" --relative-to="${MYCMD_BASE_DIR}" "${full_path}")"
+	local -r command_group="${2-}"
+
+	local relative_path
+
+	if ! relative_path=$(mycmd._path_relative_to_directory "${full_path}" "${MYCMD_SYSTEM_BASE_DIR}${command_group:+/}${command_group-}"); then
+		if [[ -v MYCMD_USER_BASE_DIR ]]; then
+			if ! relative_path=$(mycmd._path_relative_to_directory "${full_path}" "${MYCMD_USER_BASE_DIR}${command_group:+/}${command_group-}"); then
+				return 1
+			fi
+		else
+			return 1
+		fi
+	fi
+
 	echo "${relative_path}"
 }
 
-# mycmd.auto_source_mycmd_libs
-#   Walks the MyCmd directory hierarchy starting from the direct child of MYCMD_BASE_DIR
-#   down to the directory the calling command script is in and sources the library file
-#   <directory_name>-lib if it exists
-function mycmd.auto_source_mycmd_libs() {
-	local -r relative_path=$(_mycmd.running_cmd_relative_path)
+# mycmd.path_relative_to_mycmd_base
+#   Given an absolute path to a command or command group, return the relative path
+#   in comparison to either MYCMD_SYSTEM_BASE_DIR or MYCMD_USER_BASE_DIR.
+mycmd.defer_at_startup mycmd.init_bin realpath
+function mycmd.path_relative_to_mycmd_base() {
+	# We assume that full_path is going to be a canonicalized absolute path
+	local -r full_path="${1}"
 
-	# TODO Properly error on things outside of MYCMD_BASE_DIR
+	mycmd.path_relative_to_mycmd_base_with_command_group "${full_path}"
+}
+
+function _mycmd.running_cmd_relative_path() {
+	local -r running_cmd_dir="$(dirname "${BASH_SOURCE[-1]}")"
+	local relative_path
+
+	if relative_path="$(mycmd.path_relative_to_mycmd_base "${running_cmd_dir}")"; then
+		echo "${relative_path}"
+		return 0
+	else
+		mycmd.log "Error getting running command relative path."
+		return 1
+	fi
+}
+
+# mycmd.auto_source_mycmd_libs
+#   Walks the MyCmd directory hierarchy starting from the direct child of either
+#   MYCMD_SYSTEM_BASE_DIR or MYCMD_USER_BASE_DIR down to the directory the calling
+#   command script is in and sources the library file <directory_name>-lib if it
+#   exists.
+function mycmd.auto_source_mycmd_libs() {
+	local relative_path
+	if ! relative_path=$(_mycmd.running_cmd_relative_path); then
+		mycmd.err_exit 1 "Error auto sourcing libraries."
+	fi
+
 	if [[ "${relative_path}" == "." ]]; then
-		mycmd.trace "No additional libraries to automatically source, command is in ${MYCMD_BASE_DIR}."
+		mycmd.trace "No additional libraries to automatically source, command is in system or user base directory."
 		return
 	fi
 
-	# TODO: Validate that running_cmd_dir is a child path of MYCMD_BASE_DIR
 	mycmd.source_mycmd_lib "${relative_path}"
 }
 
+# _mycmd.source_local_override
+#    The local override file, if it exists, is found in MYCMD_USER_BASE_DIR.
 function _mycmd.source_local_override() {
-	local -r local_lib="${MYCMD_BASE_DIR}/mycmd-local-lib"
+	[[ -z "${MYCMD_USER_BASE_DIR-}" ]] && return 0
+
+	local -r local_lib="${MYCMD_USER_BASE_DIR}/mycmd-local-lib"
 
 	# shellcheck source=/dev/null
 	[[ -e "${local_lib}" ]] && source "${local_lib}"
-}
-
-# ------------------------------------------------------------------------------
-# Convenience functions for calling other MyCmd commands
-mycmd.defer_at_startup mycmd.init_bin sed
-function mycmd.nested_mycmd_command_line() {
-	local unset_vars
-	unset_vars="$(declare -p | grep -E "^declare [-][^ ]+x .*" | "${MYCMD_BIN[sed]}" -r -n 's/declare \-[^ ]+ ([^=]+)=.*/-u \1/p' | tr '\n' ' ')"
-
-	echo "/usr/bin/env ${unset_vars} mycmd" | tr -s '[:space:]'
 }
 
 # ------------------------------------------------------------------------------
@@ -712,4 +792,4 @@ _mycmd.source_local_override
 # Run any deferred commands
 _mycmd.run_startup_deferreds
 
-mycmd.trace "$0 sourcing complete."
+mycmd.trace "${_MYCMD_LIB_SELF_FILE} sourcing complete."
