Support minimal project.execute_tasks

diff --git a/mycmd/project/run b/mycmd/project/run
--- a/mycmd/project/run
+++ b/mycmd/project/run
@@ -32,7 +32,8 @@ readonly _TASKS='tasks'
 function parse_command_line() {
     local -n arguments_ref="${1}"
     shift
-    local -n task_positions_ref="${1}"
+    local -r task_positions_ref_name="${1}"
+    local -n task_positions_ref="${task_positions_ref_name}"
     shift
 
     local -A errors=()
@@ -73,82 +74,74 @@ function parse_command_line() {
     # tasks
     # - if global arguments are provided, -- is required
     # - otherwise, -- can be omitted
-    while (($# > 0)); do
-        if [[ "${completed_global_arguments}" = "false" ]]; then
-            case "${1}" in
-                "--${_HELP}" | "-h")
-                    arguments_ref["${_HELP}"]=true
-                    # Ignore other arguments
+    while [[ $# -gt 0 && "${completed_global_arguments}" = "false" ]]; do
+        case "${1}" in
+            "--${_HELP}" | "-h")
+                arguments_ref["${_HELP}"]=true
+                # Ignore other arguments
+                break
+                ;;
+
+            "--${_VERSION}" | "-v")
+                arguments_ref["${_VERSION}"]=true
+                # Ignore other arguments
+                break
+                ;;
+
+            "--${_PROMPT}" | "-p")
+                arguments_ref["${_PROMPT}"]=true
+                shift
+                ((arg_index += 1))
+                ;;
+
+            "--${_QUIET}" | "-q")
+                arguments_ref["${_QUIET}"]=true
+                shift
+                ((arg_index += 1))
+                ;;
+
+            "--${_VERBOSE}" | "-V")
+                arguments_ref["${_VERBOSE}"]=true
+                shift
+                ((arg_index += 1))
+                ;;
+
+            "--")
+                mycmd.trace "Switching to task arguments because of arguments separator"
+                completed_global_arguments="true"
+                shift
+                ((arg_index += 1))
+
+                if (($# > 0)); then
+                    task_positions_ref+=("${arg_index}")
+                else
+                    mycmd.log "Expecting tasks and arguments after options separator '--'."
+                    errors["${_TASKS}"]=1
+                fi
+                ;;
+
+            "--"* | "-"*)
+                mycmd.log "Unknown flag or argument: '${1}'"
+                errors['UNKNOWN']=1
+                shift
+                ((arg_index += 1))
+                ;;
+
+            *)
+                if [[ "${arguments_ref["${_QUIET}"]}" = "true" || "${arguments_ref["${_VERBOSE}"]}" = "true" || "${arguments_ref["${_VERBOSE}"]}" = "true" ]]; then
+                    mycmd.log "Tasks and arguments must be separated from options by '--'."
+                    errors["${_TASKS}"]=1
                     break
-                    ;;
-
-                "--${_VERSION}" | "-v")
-                    arguments_ref["${_VERSION}"]=true
-                    # Ignore other arguments
-                    break
-                    ;;
-
-                "--${_PROMPT}" | "-p")
-                    arguments_ref["${_PROMPT}"]=true
-                    shift
-                    ((arg_index += 1))
-                    ;;
-
-                "--${_QUIET}" | "-q")
-                    arguments_ref["${_QUIET}"]=true
-                    shift
-                    ((arg_index += 1))
-                    ;;
-
-                "--${_VERBOSE}" | "-V")
-                    arguments_ref["${_VERBOSE}"]=true
-                    shift
-                    ((arg_index += 1))
-                    ;;
-
-                "--")
-                    mycmd.trace "Switching to task arguments because of arguments separator"
+                else
+                    mycmd.trace "Switching to global arguments parsing."
+                    task_positions_ref+=("${arg_index}")
                     completed_global_arguments="true"
-                    shift
-                    ((arg_index += 1))
-
-                    if (($# > 0)); then
-                        task_positions_ref+=("${arg_index}")
-                    else
-                        mycmd.log "Expecting tasks and arguments after options separator '--'."
-                        errors["${_TASKS}"]=1
-                    fi
-                    ;;
-
-                "--"* | "-"*)
-                    mycmd.log "Unknown flag or argument: '${1}'"
-                    errors['UNKNOWN']=1
-                    shift
-                    ((arg_index += 1))
-                    ;;
-
-                *)
-                    if [[ "${arguments_ref["${_QUIET}"]}" = "true" || "${arguments_ref["${_VERBOSE}"]}" = "true" || "${arguments_ref["${_VERBOSE}"]}" = "true" ]]; then
-                        mycmd.log "Tasks and arguments must be separated from options by '--'."
-                        errors["${_TASKS}"]=1
-                        break
-                    else
-                        mycmd.trace "Switching to global arguments parsing."
-                        task_positions_ref+=("${arg_index}")
-                        completed_global_arguments="true"
-                    fi
-                    ;;
-            esac
-        else
-            ((arg_index += 1))
-
-            if [[ "${1}" = ";" && "$#" -gt 0 ]]; then
-                task_positions_ref+=("${arg_index}")
-            fi
-
-            shift
-        fi
+                fi
+                ;;
+        esac
     done
+
+    project.extract_task_positions "${task_positions_ref_name}" "${arg_index}" "${@}"
 
     mycmd.trace "Parsed arguments:"
     local argument
@@ -172,6 +165,90 @@ function parse_command_line() {
     fi
 
     (("${#errors[@]}" == 0))
+}
+
+function new_execution_task() {
+    project.task._new_task \
+        execution_tasks \
+        execution_arguments \
+        execution_task_argument_ref_names \
+        execution_task_argument_indices \
+        execution_task_argument_counts \
+        "${@}"
+}
+
+function get_execution_task() {
+    local -Ar _dummy_filesets=()
+
+    project.task._get_task \
+        execution_tasks \
+        _dummy_filesets \
+        execution_task_argument_ref_names \
+        execution_task_argument_indices \
+        execution_task_argument_counts \
+        "${@}"
+}
+
+function execute_tasks() {
+    local -n execution_arguments_ref="${1}"
+    shift
+    mycmd.trace "Execution arguments: ${execution_arguments_ref[*]}"
+    local -n task_positions_ref="${1}"
+    shift
+
+    local -A execution_tasks=()
+    local -a execution_arguments=()
+    local -A execution_task_argument_ref_names=()
+    local -A execution_task_argument_indices=()
+    local -A execution_task_argument_counts=()
+    local -a execution_task_names=()
+
+    local -i max_argument="${#execution_arguments_ref[@]}"
+    local -i index
+    local -ri max_index=$(("${#task_positions_ref[@]}" - 1))
+
+    local start
+    local end
+    local len
+    local next_index
+    local task_name
+
+    for ((index = 0; index < "${#task_positions_ref[@]}"; index++)); do
+        start=${task_positions_ref[index]}
+        task_name="${execution_arguments_ref[${start}]}"
+        start=$((start + 1))
+
+        if ((index < max_index)); then
+            next_index=$((index + 1))
+            end=$((${task_positions_ref[${next_index}]} - 1))
+        else
+            end=${max_argument}
+        fi
+        len=$((end - start))
+
+        set -- "${execution_arguments_ref[@]:start:len}"
+
+        new_execution_task "${task_name}" execute_task "${@}"
+        execution_task_names+=("${task_name}")
+    done
+
+    local task_name
+    for task_name in "${execution_task_names[@]}"; do
+        project.verbose "Dispatching task '${task_name}'."
+        local -A task=()
+
+        if ! get_execution_task "${task_name}" task; then
+            mycmd.log "Error getting task '${task_name}'."
+        fi
+
+        local exit_code=0
+
+        project.execute_task task || exit_code=$?
+
+        if ((exit_code != 0)); then
+            exit "${exit_code}"
+        fi
+    done
 }
 
 function mycmd.main() {
@@ -222,38 +299,8 @@ function mycmd.main() {
     fi
 
     local -a arguments=("${@}")
-    local -i max_argument=$#
+    local exit_code=0
+    execute_tasks arguments task_positions || exit_code=$?
 
-    local -i index
-    local -ri max_index=$(("${#task_positions[@]}" - 1))
-
-    local start
-    local end
-    local len
-    local next_index
-
-    for ((index = 0; index < "${#task_positions[@]}"; index++)); do
-        start=${task_positions[index]}
-
-        if ((index < max_index)); then
-            next_index=$((index + 1))
-            end=$((${task_positions[${next_index}]} - 1))
-        else
-            end=${max_argument}
-        fi
-        len=$((end - start))
-
-        set -- "${arguments[@]:start:len}"
-
-        mycmd.trace "Set task and arguments to ${*}"
-        local exit_code=0
-
-        project.execute_task "${@}" || exit_code=$?
-
-        if ((exit_code != 0)); then
-            exit "${exit_code}"
-        fi
-    done
-
-    exit 0
+    exit "${exit_code}"
 }
