Implement platform standard user directories
Use the platform standard user directories for cache and config. Allow
these to be overridden for testing purposes.

Added functions for commands and command groups to get files scoped to
them.

Also fix a small bug and typos in the pathname library.

diff --git a/testing/tests/command-group-test b/testing/tests/command-group-test
--- a/testing/tests/command-group-test
+++ b/testing/tests/command-group-test
@@ -6,21 +6,37 @@ if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
     echo >&2 "Error fetching test directory."
     exit 1
 fi
+readonly TEST_DIRECTORY
 
 if ! TEST_VENDOR_DIRECTORY=$(cd "${TEST_DIRECTORY}/../vendor" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching test vendor directory."
     exit 1
 fi
+readonly TEST_VENDOR_DIRECTORY
 
 if ! TEST_USER_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../user-base" && pwd -P); then
     echo >&2 "Error fetching test user base directory."
     exit 1
 fi
+readonly TEST_USER_LIB_DIRECTORY
 
 if ! MYCMD_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching MyCmd lib directory."
     exit 1
 fi
+readonly MYCMD_LIB_DIRECTORY
+
+if ! TEST_USER_DIR="$(mktemp -q -d -t "test-user-XXXXXX")"; then
+    echo >&2 "Error getting temporary directory for test user directory."
+    exit 1
+fi
+
+# On Mac OS, the TMPDIR is a symlink, so this gets the resolved path
+if ! TEST_USER_DIR=$(cd "${TEST_USER_DIR}" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching test user directory."
+    exit 1
+fi
+readonly TEST_USER_DIR
 
 function test_mycmd_command_group_lib_is_loaded() {
     assertTrue 'MyCmd Lib Command Group Support Lib is loaded' '[ -v _MYCMD_COMMAND_GROUP_LIB ]'
@@ -57,7 +73,7 @@ function test_base_mycmd_command_group() {
         "${child_command_group_count}" "${#child_command_groups[@]}"
 }
 
-# shellcheck disable=SC2034,SC2312
+# shellcheck disable=SC2016,SC2034,SC2154,SC2312
 function test_shell_extended_command_group() {
     local -A shell_extended_command_group
     mycmd:registry.get_command_group "mycmd/shell/extended" shell_extended_command_group
@@ -75,15 +91,27 @@ function test_shell_extended_command_group() {
         "$(mycmd:command_group.get_help_text shell_extended_command_group)"
     assertEquals "1.0" "$(mycmd:command_group.get_version shell_extended_command_group)"
 
-    mycmd.trace "Loading the command groups:"
     assertTrue 'Successfullly loads the command groups' \
         'mycmd:command_group.load_command_group shell_extended_command_group'
 
     assertTrue 'MyCmd Shell Group Lib Loaded' '[ -v _MYCMD_SHELL_LIB ]'
     assertTrue 'MyCmd Shell Extended Group Lib Loaded' '[ -v _MYCMD_SHELL_EXTENDED_LIB ]'
+
+    local -r expected_config_file="${TEST_USER_DIR}/config/mycmd/shell/extended/config.json"
+    assertEquals "${expected_config_file}" "${_MYCMD_SHELL_EXTENDED_CONFIG}"
+    assertTrue "'${expected_config_file}' exists" \
+        '[[ -e "${expected_config_file}" ]]'
+
+    local -r expected_cache_file="${TEST_USER_DIR}/cache/mycmd/shell/extended/cache-file"
+    assertEquals "${expected_cache_file}" "${_MYCMD_SHELL_EXTENDED_CACHE}"
+    assertTrue "'${expected_cache_file}' exists" \
+        '[[ -e "${expected_cache_file}" ]]'
 }
 
 function oneTimeSetUp() {
+    export _MYCMD_TEST_USER_CACHE_HOME="${TEST_USER_DIR}/cache/mycmd"
+    export _MYCMD_TEST_USER_CONFIG_HOME="${TEST_USER_DIR}/config/mycmd"
+
     # shellcheck source=../../mycmd/mycmd-command-group-lib
     . "${MYCMD_LIB_DIRECTORY}/mycmd-command-group-lib"
 
@@ -93,6 +121,12 @@ function oneTimeSetUp() {
         "MyCmd Short Description" \
         "This is a help\nMessage" \
         "0.1"
+}
+
+function oneTimeTearDown() {
+    if [[ -d "${TEST_USER_DIR}" ]]; then
+        rm -rf "${TEST_USER_DIR}" || true
+    fi
 }
 
 # shellcheck source=../vendor/shunit2
diff --git a/testing/tests/command-test b/testing/tests/command-test
--- a/testing/tests/command-test
+++ b/testing/tests/command-test
@@ -6,22 +6,37 @@ if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
     echo >&2 "Error fetching test directory."
     exit 1
 fi
+readonly TEST_DIRECTORY
 
 if ! TEST_VENDOR_DIRECTORY=$(cd "${TEST_DIRECTORY}/../vendor" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching test vendor directory."
     exit 1
 fi
+readonly TEST_VENDOR_DIRECTORY
 
 if ! MYCMD_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching MyCmd lib directory."
     exit 1
 fi
+readonly MYCMD_LIB_DIRECTORY
+
+if ! TEST_USER_DIR="$(mktemp -q -d -t "test-user-XXXXXX")"; then
+    echo >&2 "Error getting temporary directory for test user directory."
+    exit 1
+fi
+
+# On Mac OS, the TMPDIR is a symlink, so this gets the resolved path
+if ! TEST_USER_DIR=$(cd "${TEST_USER_DIR}" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching test user directory."
+    exit 1
+fi
+readonly TEST_USER_DIR
 
 function test_mycmd_command_lib_is_loaded() {
     assertTrue 'MyCmd Lib Command Support Lib is loaded' '[ -v _MYCMD_COMMAND_LIB ]'
 }
 
-# shellcheck disable=SC2034,SC2154,SC2312
+# shellcheck disable=SC2016,SC2034,SC2154,SC2312
 function test_test-command() {
     local -A command
     mycmd:registry.get_command "mycmd/test-command" command
@@ -41,14 +56,33 @@ function test_test-command() {
 
     assertTrue 'test-command can be executed' \
         'mycmd:command.execute command'
+
+    local -r expected_config_file="${TEST_USER_DIR}/config/mycmd/test-command/config.ini"
+    assertEquals "${expected_config_file}" "${_TEST_COMMAND_CONFIG}"
+    assertTrue "'${expected_config_file}' exists" \
+        '[[ -e "${expected_config_file}" ]]'
+
+    local -r expected_cache_file="${TEST_USER_DIR}/cache/mycmd/test-command/cache-file"
+    assertEquals "${expected_cache_file}" "${_TEST_COMMAND_CACHE}"
+    assertTrue "'${expected_cache_file}' exists" \
+        '[[ -e "${expected_cache_file}" ]]'
 }
 
 function oneTimeSetUp() {
+    export _MYCMD_TEST_USER_CACHE_HOME="${TEST_USER_DIR}/cache/mycmd"
+    export _MYCMD_TEST_USER_CONFIG_HOME="${TEST_USER_DIR}/config/mycmd"
+
     # shellcheck source=../../mycmd/mycmd-command-lib
     . "${MYCMD_LIB_DIRECTORY}/mycmd-command-lib"
 
     # This will be called in mycmd-lib normally
     mycmd:registry.discover_command_groups_and_commands
+}
+
+function oneTimeTearDown() {
+    if [[ -d "${TEST_USER_DIR}" ]]; then
+        rm -rf "${TEST_USER_DIR}" || true
+    fi
 }
 
 # shellcheck source=../vendor/shunit2
diff --git a/testing/tests/platform-support-test b/testing/tests/platform-support-test
--- a/testing/tests/platform-support-test
+++ b/testing/tests/platform-support-test
@@ -6,16 +6,25 @@ if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
     echo >&2 "Error fetching test directory."
     exit 1
 fi
+readonly TEST_DIRECTORY
 
 if ! TEST_VENDOR_DIRECTORY=$(cd "${TEST_DIRECTORY}/../vendor" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching test vendor directory."
     exit 1
 fi
+readonly TEST_VENDOR_DIRECTORY
 
 if ! MYCMD_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching MyCmd lib directory."
     exit 1
 fi
+readonly MYCMD_LIB_DIRECTORY
+
+if ! TMP_WORKING_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../tmp" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching the temp working directory."
+    exit 1
+fi
+readonly TMP_WORKING_DIRECTORY
 
 function test_mycmd_platform_support_lib_is_loaded() {
     assertTrue 'MyCmd Platform Support Lib is loaded' '[ -v _MYCMD_PLATFORM_SUPPORT_LIB ]'
@@ -54,7 +63,30 @@ function test_init_bin__exits() {
         "This should be not printed"
 }
 
+# shellcheck disable=SC2154,SC2312
+function test_user_config_home() {
+    local -r expected_user_config="${TMP_WORKING_DIRECTORY}/config/mycmd"
+    assertEquals "_MYCMD_USER_CONFIG_DIRECTORY is '${expected_user_config}'" \
+        "${expected_user_config}" "${_MYCMD_USER_CONFIG_DIRECTORY}"
+
+    local -r config_file="${expected_user_config}/logging/config.json"
+    assertEquals "${config_file}" "$(mycmd.get_user_config_file "mycmd/logging" config.json)"
+}
+
+# shellcheck disable=SC2154,SC2312
+function test_user_cache_home() {
+    local -r expected_user_cache="${TMP_WORKING_DIRECTORY}/cache/mycmd"
+    assertEquals "_MYCMD_USER_CACHE_DIRECTORY is '${expected_user_cache}'" \
+        "${expected_user_cache}" "${_MYCMD_USER_CACHE_DIRECTORY}"
+
+    local -r cache_file="${expected_user_cache}/logging/cache-file"
+    assertEquals "${cache_file}" "$(mycmd.get_user_cache_file "mycmd/logging" cache-file)"
+}
+
 function oneTimeSetUp() {
+    export _MYCMD_TEST_USER_CACHE_HOME="${TMP_WORKING_DIRECTORY}/cache/mycmd"
+    export _MYCMD_TEST_USER_CONFIG_HOME="${TMP_WORKING_DIRECTORY}/config/mycmd"
+
     # shellcheck source=../../mycmd/mycmd-platform-support-lib
     . "${MYCMD_LIB_DIRECTORY}/mycmd-platform-support-lib"
 }
