WIP: Splitting into multiple support libraries
Does not currently work, but wanting to push a commit

diff --git a/testing/tests/command-group-test b/testing/tests/command-group-test
--- a/testing/tests/command-group-test
+++ b/testing/tests/command-group-test
@@ -12,6 +12,11 @@ if ! TEST_VENDOR_DIRECTORY=$(cd "${TEST_DIRECTORY}/../vendor" &>/dev/null && pwd
     exit 1
 fi
 
+if ! TEST_USER_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../user-base" && pwd -P); then
+    echo >&2 "Error fetching test user base directory."
+    exit 1
+fi
+
 if ! MYCMD_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching MyCmd lib directory."
     exit 1
@@ -21,8 +26,17 @@ function test_mycmd_command_group_lib_is_loaded() {
     assertTrue 'MyCmd Lib Command Group Support Lib is loaded' '[ -v _MYCMD_COMMAND_GROUP_LIB ]'
 }
 
+# shellcheck disable=SC2312
+function test_directory_is_command_group() {
+    assertTrue "Directory '${MYCMD_LIB_DIRECTORY}/shell' is a command group" \
+        "mycmd:command_group.directory_contains_command_group ${MYCMD_LIB_DIRECTORY}/shell"
+
+    assertFalse "Directory '${MYCMD_LIB_DIRECTORY}/foo' is a not command group" \
+        "mycmd:command_group.directory_contains_command_group ${MYCMD_LIB_DIRECTORY}/foo"
+}
+
+# shellcheck disable=SC2016,SC2034,SC2154,SC2312
 function test_base_mycmd_command_group() {
-    # shellcheck disable=SC2034
     local -A mycmd_command_group
     mycmd:command_group.get_command_group mycmd mycmd_command_group
     assertEquals "mycmd" "$(mycmd:command_group.get_name mycmd_command_group)"
@@ -38,6 +52,37 @@ function test_base_mycmd_command_group() {
     assertFalse 'There is no long description defined' \
         'mycmd:command_group.get_long_description mycmd_command_group'
     assertEquals "Unknown" "$(mycmd:command_group.get_version mycmd_command_group)"
+
+    local -a parent_tree
+    mycmd:command_group.get_parent_tree mycmd_command_group parent_tree
+    assertTrue 'parent_tree has one element' '(( "${#parent_tree[@]}" == 1 ))'
+    assertSame 'only element in parent tree is "mycmd"' "${parent_tree[0]}" "mycmd"
+}
+
+# shellcheck disable=SC2016,SC2034,SC2154,SC2312
+function test_shell_complete_command_group() {
+    local -A shell_complete_command_group
+    mycmd:command_group.get_command_group "mycmd/shell/complete" shell_complete_command_group
+    assertEquals "complete" "$(mycmd:command_group.get_name shell_complete_command_group)"
+    assertEquals "mycmd/shell/complete" "$(mycmd:command_group.get_fully_qualified_name shell_complete_command_group)"
+    assertEquals "mycmd shell complete" "$(mycmd:command_group.get_namespaced_parts_as_string shell_complete_command_group)"
+    assertEquals "${TEST_USER_LIB_DIRECTORY}/shell/complete" "$(mycmd:command_group.get_source_directory shell_complete_command_group)"
+    assertEquals "${TEST_USER_LIB_DIRECTORY}/shell/complete/complete-lib" "$(mycmd:command_group.get_source_file shell_complete_command_group)"
+    assertFalse 'There is no local override source directory defined' \
+        'mycmd:command_group.get_local_override_source_directory shell_complete_command_group'
+    assertFalse 'There is no local override source file defined' \
+        'mycmd:command_group.get_local_override_source_file shell_complete_command_group'
+    assertEquals "MyCmd Command Group mycmd shell complete" "$(mycmd:command_group.get_short_description shell_complete_command_group)"
+    assertFalse 'There is no long description defined' \
+        'mycmd:command_group.get_long_description shell_complete_command_group'
+    assertEquals "Unknown" "$(mycmd:command_group.get_version shell_complete_command_group)"
+
+    local -a parent_tree
+    mycmd:command_group.get_parent_tree shell_complete_command_group parent_tree
+    assertTrue 'parent_tree has three elements' '(( "${#parent_tree[@]}" == 3 ))'
+    assertSame 'first element in parent tree is "mycmd"' "${parent_tree[0]}" "mycmd"
+    assertSame 'second element in parent tree is "mycmd/shell"' "${parent_tree[1]}" "mycmd/shell"
+    assertSame 'third element in parent tree is "mycmd/shell/complete"' "${parent_tree[2]}" "mycmd/shell/complete"
 }
 
 function oneTimeSetUp() {
@@ -47,6 +92,12 @@ function oneTimeSetUp() {
     # TODO: This will be added by default in the future
     _MYCMD_COMMAND_GROUP_SOURCE_DIRECTORIES["mycmd"]="${MYCMD_LIB_DIRECTORY}"
     _MYCMD_COMMAND_GROUP_SOURCE_FILES["mycmd"]="${MYCMD_LIB_DIRECTORY}/mycmd-lib"
+
+    _MYCMD_COMMAND_GROUP_SOURCE_DIRECTORIES["mycmd/shell"]="${MYCMD_LIB_DIRECTORY}/shell"
+    _MYCMD_COMMAND_GROUP_SOURCE_FILES["mycmd/shell"]="${MYCMD_LIB_DIRECTORY}/shell/shell-lib"
+
+    _MYCMD_COMMAND_GROUP_SOURCE_DIRECTORIES["mycmd/shell/complete"]="${TEST_USER_LIB_DIRECTORY}/shell/complete"
+    _MYCMD_COMMAND_GROUP_SOURCE_FILES["mycmd/shell/complete"]="${TEST_USER_LIB_DIRECTORY}/shell/complete/complete-lib"
 }
 
 # shellcheck source=../vendor/shunit2
