Rename constant to reflect the directory name
TEST_DIRECTORY -> TESTS_DIRECTORY, since the directory is named
`testing/tests`.

diff --git a/testing/tests/environment-test b/testing/tests/environment-test
--- a/testing/tests/environment-test
+++ b/testing/tests/environment-test
@@ -2,15 +2,16 @@
 # -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
 # shellcheck shell=bash disable=SC2317
 
-if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
-    echo >&2 "Error fetching test directory."
+if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching tests directory."
     exit 1
 fi
-readonly TEST_DIRECTORY
+readonly TESTS_DIRECTORY
 
-source "${TEST_DIRECTORY}/testing-support-lib"
+# shellcheck source=./testing-support-lib
+source "${TESTS_DIRECTORY}/testing-support-lib"
 
-if ! ADDITIONAL_BASE=$(cd "${TEST_DIRECTORY}/../additional-base" &>/dev/null && pwd -P); then
+if ! ADDITIONAL_BASE=$(cd "${TESTS_DIRECTORY}/../additional-base" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching additional base directory."
     exit 1
 fi
@@ -33,7 +34,7 @@ function test_get_absolute_path() {
 
     # shellcheck disable=SC2154
     assertSame "${TEST_USER_LIB_DIRECTORY}" \
-        "$(mycmd._get_absolute_path "${TEST_DIRECTORY}/../user-base")"
+        "$(mycmd._get_absolute_path "${TESTS_DIRECTORY}/../user-base")"
 }
 
 # shellcheck disable=SC2016,SC2153,SC2154
diff --git a/testing/tests/function-redefinition-test b/testing/tests/function-redefinition-test
--- a/testing/tests/function-redefinition-test
+++ b/testing/tests/function-redefinition-test
@@ -2,13 +2,13 @@
 # -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
 # shellcheck shell=bash
 
-if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
-    echo >&2 "Error fetching test directory."
+if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching tests directory."
     exit 1
 fi
-readonly TEST_DIRECTORY
+readonly TESTS_DIRECTORY
 
-source "${TEST_DIRECTORY}/testing-support-lib"
+source "${TESTS_DIRECTORY}/testing-support-lib"
 
 function test_mycmd_base_loading_lib_is_loaded() {
     assertTrue 'MyCmd Loading Base Lib is loaded' '[ -v _MYCMD_LOADING_BASE_LIB ]'
diff --git a/testing/tests/pathname-test b/testing/tests/pathname-test
--- a/testing/tests/pathname-test
+++ b/testing/tests/pathname-test
@@ -2,18 +2,13 @@
 # -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
 # shellcheck shell=bash disable=SC2317
 
-if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
-    echo >&2 "Error fetching test directory."
+if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching tests directory."
     exit 1
 fi
-readonly TEST_DIRECTORY
+readonly TESTS_DIRECTORY
 
-source "${TEST_DIRECTORY}/testing-support-lib"
-
-if ! MYCMD_BIN_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../bin" &>/dev/null && pwd -P); then
-    echo >&2 "Error fetching MyCmd tmp directory."
-    exit 1
-fi
+source "${TESTS_DIRECTORY}/testing-support-lib"
 
 function test_pathname_lib_is_loaded() {
     assertTrue 'MyCmd Pathname Support Lib is loaded' '[ -v _MYCMD_PATHNAME_LIB ]'
@@ -34,7 +29,7 @@ function test_is_valid_absolute_path() {
         'mycmd.is_valid_absolute_path "${MYCMD_LIB_DIRECTORY}/mycmd-lib"'
 }
 
-# shellcheck disable=SC2016
+# shellcheck disable=SC2016,SC2154
 function test_is_valid_absolute_path_of_executed_file() {
     assertFalse '../../bin/mycmd is not an absolute path to an executable file' \
         'mycmd.is_valid_absolute_path_of_executable_file ../../bin/mycmd'
@@ -82,13 +77,13 @@ function test_path_relative_to_directory() {
         'mycmd._path_relative_to_directory "${MYCMD_LIB_DIRECTORY}/non-existing" "${MYCMD_LIB_DIRECTORY}"'
 
     assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not an absolute path" \
-        'mycmd._path_relative_to_directory "${TEST_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/../mycmd"'
+        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/../mycmd"'
 
     assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing does not exist" \
-        'mycmd._path_relative_to_directory "${TEST_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/non-existing"'
+        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/non-existing"'
 
-    assertFalse "${TEST_DIRECTORY} is not relative to ${MYCMD_LIB_DIRECTORY}" \
-        'mycmd._path_relative_to_directory "${TEST_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}"'
+    assertFalse "${TESTS_DIRECTORY} is not relative to ${MYCMD_LIB_DIRECTORY}" \
+        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}"'
 
     assertEquals "project" \
         "$(mycmd._path_relative_to_directory "${MYCMD_LIB_DIRECTORY}/project" "${MYCMD_LIB_DIRECTORY}")"
diff --git a/testing/tests/registry-test b/testing/tests/registry-test
--- a/testing/tests/registry-test
+++ b/testing/tests/registry-test
@@ -2,15 +2,15 @@
 # -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
 # shellcheck shell=bash
 
-if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
-    echo >&2 "Error fetching test directory."
+if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
+    echo >&2 "Error fetching tests directory."
     exit 1
 fi
-readonly TEST_DIRECTORY
+readonly TESTS_DIRECTORY
 
-source "${TEST_DIRECTORY}/testing-support-lib"
+source "${TESTS_DIRECTORY}/testing-support-lib"
 
-if ! MYCMD_SUPPORT_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../support" &>/dev/null && pwd -P); then
+if ! MYCMD_SUPPORT_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../../support" &>/dev/null && pwd -P); then
     echo >&2 "Error fetching MyCmd support directory."
     exit 1
 fi
@@ -103,8 +103,8 @@ function test_get_invalid_command_groups() {
 
 # shellcheck disable=SC2016,SC2154
 function test_file_is_command() {
-    assertFalse "${TEST_DIRECTORY}/../../mycmd/project/run is not absolute and not a command" \
-        'mycmd:registry._file_is_command "${TEST_DIRECTORY}/../../mycmd/project/run"'
+    assertFalse "${TESTS_DIRECTORY}/../../mycmd/project/run is not absolute and not a command" \
+        'mycmd:registry._file_is_command "${TESTS_DIRECTORY}/../../mycmd/project/run"'
 
     assertFalse "${MYCMD_LIB_DIRECTORY}/mycmd-lib is not executable and not a command" \
         'mycmd:registry._file_is_command "${MYCMD_LIB_DIRECTORY}/mycmd-lib"'
diff --git a/testing/tests/testing-support-lib b/testing/tests/testing-support-lib
--- a/testing/tests/testing-support-lib
+++ b/testing/tests/testing-support-lib
@@ -6,17 +6,17 @@
 [[ -n "${_MYCMD_TEST_SUPPORT_LIB:-}" ]] && return
 readonly _MYCMD_TEST_SUPPORT_LIB=1
 
-if [[ ! -v TEST_DIRECTORY ]]; then
-    if ! TEST_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
-        echo >&2 "Error fetching test directory."
+if [[ ! -v TESTS_DIRECTORY ]]; then
+    if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
+        echo >&2 "Error fetching tests directory."
         exit 1
     fi
-    export TEST_DIRECTORY
-    readonly TEST_DIRECTORY
+    export TESTS_DIRECTORY
+    readonly TESTS_DIRECTORY
 fi
 
 if [[ ! -v TEST_VENDOR_DIRECTORY ]]; then
-    if ! TEST_VENDOR_DIRECTORY=$(cd "${TEST_DIRECTORY}/../vendor" &>/dev/null && pwd -P); then
+    if ! TEST_VENDOR_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../vendor" &>/dev/null && pwd -P); then
         echo >&2 "Error fetching test vendor directory."
         exit 1
     fi
@@ -25,12 +25,21 @@ if [[ ! -v TEST_VENDOR_DIRECTORY ]]; then
 fi
 
 if [[ ! -v MYCMD_LIB_DIRECTORY ]]; then
-    if ! MYCMD_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
+    if ! MYCMD_LIB_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../../mycmd" &>/dev/null && pwd -P); then
         echo >&2 "Error fetching MyCmd lib directory."
         exit 1
     fi
     export MYCMD_LIB_DIRECTORY
     readonly MYCMD_LIB_DIRECTORY
+fi
+
+if [[ ! -v MYCMD_BIN_DIRECTORY ]]; then
+    if ! MYCMD_BIN_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../../bin" &>/dev/null && pwd -P); then
+        echo >&2 "Error fetching MyCmd tmp directory."
+        exit 1
+    fi
+    export MYCMD_BIN_DIRECTORY
+    readonly MYCMD_BIN_DIRECTORY
 fi
 
 function start_tracing() {
@@ -51,7 +60,7 @@ function start_tracing() {
 }
 
 function setup_test_user_lib_directory() {
-    if ! TEST_USER_LIB_DIRECTORY=$(cd "${TEST_DIRECTORY}/../user-base" && pwd -P); then
+    if ! TEST_USER_LIB_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../user-base" && pwd -P); then
         echo >&2 "Error fetching test user base directory."
         exit 1
     fi
@@ -78,7 +87,7 @@ function setup_test_user_directory() {
 }
 
 function setup_mycmd_tmp_directory() {
-    if ! MYCMD_TMP_DIRECTORY=$(cd "${TEST_DIRECTORY}/../../tmp" &>/dev/null && pwd -P); then
+    if ! MYCMD_TMP_DIRECTORY=$(cd "${TESTS_DIRECTORY}/../../tmp" &>/dev/null && pwd -P); then
         echo >&2 "Error fetching MyCmd tmp directory."
         exit 1
     fi
